import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import { DevNavitgation } from "@/components/common/DevNavitgation";
import { Gnb } from "@/components/common/gnb/Gnb";
import { Tab } from "@/components/common/tab/Tab";

const pretendard = localFont({
  src: "../assets/font/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "무빙",
  description: "Generated by create next app",
};

const tabList = [
  { name: "전체", href: "/" },
  { name: "리뷰", href: "/review" },
  { name: "찜한 기사", href: "/favoriteMover" },
  { name: "기사 검색", href: "/searchMover" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <Providers>
          <Gnb />

          <Tab tabList={tabList} />
          {children}
          <DevNavitgation />
        </Providers>
      </body>
    </html>
  );
}
